const zero = document.querySelector('.zeroKey')
const one = document.querySelector('.oneKey')
const two = document.querySelector('.twoKey')
const three = document.querySelector('.threeKey')
const four = document.querySelector('.fourKey')
const five = document.querySelector('.fiveKey')
const six = document.querySelector('.sixKey')
const seven = document.querySelector('.sevenKey')
const eight = document.querySelector('.eightKey')
const nine = document.querySelector('.nineKey')

const ce = document.querySelector('.ceKey')
const c = document.querySelector('.cKey')
const x = document.querySelector('.xKey')
const divide = document.querySelector('.divideKey')